# author: Lexi Zhou


eventcodedict_partial ={1: 'Servo R1 open',
                        3: 'Servo R2 open',
                        5: 'Servo R3 open',
                        7: 'Servo R4 open',
                        9: 'Mouse in hall R1',
                        11: 'Enter R1',
                        12: 'Reject R1',
                        13: 'Quit R1',
                        14: 'R1 reward tone',
                        15: 'R1 no-reward tone',
                        16: 'R1 reward taken',
                        17: 'R1 0% offer',
                        18: 'R1 20% offer',
                        19: 'R1 80% offer',
                        20: 'R1 100% offer',
                        23: 'Enter R2',
                        24: 'Reject R2',
                        25: 'Quit R2',
                        26: 'R2 reward tone',
                        27: 'R2 no-reward tone',
                        28: 'R2 reward taken',
                        29: 'R2 0% offer',
                        30: 'R2 20% offer',
                        31: 'R2 80% offer',
                        32: 'R2 100% offer',
                        35: 'Enter R3',
                        36: 'Reject R3',
                        37: 'Quit R3',
                        38: 'R3 reward tone',
                        39: 'R3 no-reward tone',
                        40: 'R3 reward taken',
                        41: 'R3 0% offer',
                        42: 'R3 20% offer',
                        43: 'R3 80% offer',
                        44: 'R3 100% offer',
                        47: 'Enter R4',
                        48: 'Reject R4',
                        49: 'Quit R4',
                        50: 'R4 reward tone',
                        51: 'R4 no-reward tone',
                        52: 'R4 reward taken',
                        53: 'R4 0% offer',
                        54: 'R4 20% offer',
                        55: 'R4 80% offer',
                        56: 'R4 100% offer',
                        61: 'SHARP Entry R1',
                        62: 'SHARP Accept R1',
                        64: 'SHARP Entry R2',
                        65: 'SHARP Accept R2',
                        67: 'SHARP Entry R3',
                        68: 'SHARP Accept R3',
                        70: 'SHARP Entry R4',
                        71: 'SHARP Accept R4',
                        99: 'Stimulation On',
                        199: 'Stimulation Off'}

eventcodedict_full = {1: 'Servo R1 open',
                      2: 'Servo R1 closed',
                      3: 'Servo R2 open',
                      4: 'Servo R2 closed',
                      5: 'Servo R3 open',
                      6:'Servo R3 closed',
                      7: 'Servo R4 open',
                      8: 'Servo R4 closed',
                      9: 'Mouse in hall R1',
                      10: 'Mouse in offer zone R1',
                      11: 'Enter R1',
                      12: 'Reject R1',
                      13: 'Quit R1',
                      14: 'R1 reward tone',
                      15: 'R1 no-reward tone',
                      16: 'R1 reward taken',
                      17: 'R1 0% offer',
                      18: 'R1 20% offer',
                      19: 'R1 80% offer',
                      20: 'R1 100% offer',
                      21: 'Mouse in hall R2',
                      22: 'Mouse in offer zone R2',
                      23: 'Enter R2',
                      24: 'Reject R2',
                      25: 'Quit R2',
                      26: 'R2 reward tone',
                      27: 'R2 no-reward tone',
                      28: 'R2 reward taken',
                      29: 'R2 0% offer',
                      30: 'R2 20% offer',
                      31: 'R2 80% offer',
                      32: 'R2 100% offer',
                      33: 'Mouse in hall R3',
                      34: 'Mouse in offer zone R3',
                      35: 'Enter R3',
                      36: 'Reject R3',
                      37: 'Quit R3',
                      38: 'R3 reward tone',
                      39: 'R3 no-reward tone',
                      40: 'R3 reward taken',
                      41: 'R3 0% offer',
                      42: 'R3 20% offer',
                      43: 'R3 80% offer',
                      44: 'R3 100% offer',
                      45: 'Mouse in hall R4',
                      46: 'Mouse in offer zone R4',
                      47: 'Enter R4',
                      48: 'Reject R4',
                      49: 'Quit R4',
                      50: 'R4 reward tone',
                      51: 'R4 no-reward tone',
                      52: 'R4 reward taken',
                      53: 'R4 0% offer',
                      54: 'R4 20% offer',
                      55: 'R4 80% offer',
                      56: 'R4 100% offer',
                      57:'R1 waited & rewarded',
                      58: 'R2 waited & rewarded',
                      59: 'R3 waited & rewarded',
                      60:'R4 waited & rewarded',
                      61: 'SHARP Entry R1',
                      62: 'SHARP Accept R1',
                      63: 'SHARP Exit R1',
                      64: 'SHARP Entry R2',
                      65: 'SHARP Accept R2',
                      66: 'SHARP Exit R2',
                      67: 'SHARP Entry R3',
                      68: 'SHARP Accept R3',
                      69: 'SHARP Exit R3',
                      70: 'SHARP Entry R4',
                      71: 'SHARP Accept R4',
                      72: 'SHARP Exit R4',
                      73: 'R1 Reward Revealed',
                      74: 'R1 Reward Withheld',
                      75: 'R1 Quit',
                      76: 'R1 Hard Reject',
                      99: 'Stimulation On',
                      199: 'Stimulation Off'}
